---
name: Algorithm-SVMLight
version: 0.09
author:
  - 'Ken Williams, E<lt>kwilliams@cpan.orgE<gt>'
abstract: Perl interface to SVMLight Machine-Learning Package
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Module::Build: 0.21
  Test::More: 0
provides:
  Algorithm::SVMLight:
    file: lib/Algorithm/SVMLight.pm
    version: 0.09
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
