---
name: Algorithm-SVMLight
version: 0.02
author:
  - Ken Williams, E<lt>kwilliams@cpan.orgE<gt>
abstract: Perl interface to SVMLight Machine-Learning Package
license: perl
build_requires:
  Module::Build: 0.21
  Test::More: 0
provides:
  Algorithm::SVMLight:
    file: lib/Algorithm/SVMLight.pm
    version: 0.02
generated_by: Module::Build version 0.2611
